[project]
name = "uptime-monitor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "black>=25.1.0",
    "fastapi[all,standard]>=0.115.8",
    "httpx>=0.28.1",
]
